<a href="https://colab.research.google.com/github/HiroshiATakano/GitHub/blob/master/Numpy100Knocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
import shutil

path = os.getcwd()

print(path)

try:
    os.chdir(path + "/drive/My Drive/Numpy_100_Knocks")
except:
    pass

os.getcwd()

/content


'/content/drive/My Drive/Numpy_100_Knocks'

In [ ]:
!ls

 100_Numpy_exercises.ipynb			    Matplotlib_20Knocks.ipynb
 100_Numpy_exercises.md				    Numpy100Knocks.ipynb
 100_Numpy_exercises_with_hints.md		   'Numpy と Scipy.ipynb'
 100_Numpy_exercises_with_hints_with_solutions.md   __pycache__
 100_Numpy_exercises_with_solutions.md		    README.md
 100_Numpy_random.ipynb				    requirements.txt
 generators.py					    Sample.gsheet
 initialise.py					    source
 LICENSE.txt


In [ ]:
!pip install mdutils

  Created wheel for mdutils: filename=mdutils-1.3.0-cp37-none-any.whl size=19466 sha256=26e01ced0151fde1467228b0139c055bed0fba9eaaa7bf03a74f18dfd47f5114
  Stored in directory: /root/.cache/pip/wheels/af/fa/1c/7b13e92bdfc39eda5970b21a15f04f6a5158dea4e3f459854d
Successfully built mdutils


In [ ]:
%run initialise.py

In [ ]:
!cat initialise.py

import numpy as np

import generators as ge


def question(n):
    print(f'{n}. ' + ge.QHA[f'q{n}'])


def hint(n):
    print(ge.QHA[f'h{n}'])


def answer(n):
    print(ge.QHA[f'a{n}'])


def pick():
    n = np.random.randint(1, 100)
    question(n)


In [ ]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a.itemsize

8

In [ ]:
hint(5)

hint: np.info


In [ ]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
a = np.arange(10,50)

In [ ]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
#9
np.arange(3*3).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#10
a = np.array([1,2,0,0,4,0])
nz = np.nonzero(a)
nz

(array([0, 1, 4]),)

In [ ]:
a[nz]

array([1, 2, 4])

In [ ]:
#11
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#12
a = np.random.random(3*3*3)
a

array([0.5468047 , 0.61861438, 0.3733338 , 0.43619999, 0.51743916,
       0.55871831, 0.81301315, 0.33244037, 0.31611356, 0.01348704,
       0.29678975, 0.04021111, 0.91888312, 0.20309299, 0.37056307,
       0.28821647, 0.24144235, 0.91996349, 0.37730527, 0.19926138,
       0.77704291, 0.77535563, 0.33661368, 0.35579921, 0.57948468,
       0.02597726, 0.28149245])

In [ ]:
a.reshape(3,3,3)

array([[[0.5468047 , 0.61861438, 0.3733338 ],
        [0.43619999, 0.51743916, 0.55871831],
        [0.81301315, 0.33244037, 0.31611356]],

       [[0.01348704, 0.29678975, 0.04021111],
        [0.91888312, 0.20309299, 0.37056307],
        [0.28821647, 0.24144235, 0.91996349]],

       [[0.37730527, 0.19926138, 0.77704291],
        [0.77535563, 0.33661368, 0.35579921],
        [0.57948468, 0.02597726, 0.28149245]]])

In [ ]:
#13
a = np.random.random((10,10))
a.min()

0.00807992600223395

In [ ]:
print(f'max:{a.max()} min:{a.min()}')

max:0.9726643103274936 min:0.00807992600223395


In [ ]:
#14
a = np.random.random(10)
print(f'平均:{a.mean()}')

平均:0.2385731373074881


In [30]:
#15
z = np.ones((10,10))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
#16
z = np.ones((5,5))
z = np.pad(z,pad_width=1,mode='constant',constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [34]:
#17
0*np.nan

nan

In [35]:
np.nan == np.nan

False

In [36]:
np.inf > np.nan

False

In [37]:
np.nan - np.nan

nan

In [39]:
np.nan in set([np.nan])

True

In [40]:
0.3 == 3*0.1

False

In [45]:
#18
z = np.diag(1+np.arange(5),k=-1)
z

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [51]:
#19
z = np.zeros((8,8),dtype=int)
z[::2,::2]=1
z[1::2,1::2]=1
z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [57]:
#20
print(np.unravel_index(7,(6,7,8)))

(0, 0, 7)


In [54]:
6*7*8

336